apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: webserver
  newName: ffelipelimao/gitops
  newTag: baaea8fdded8def690edd956eb94eda5d55ff273
